
server:
  port: 38180
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true


spring:
#  main:
#    web-application-type: none


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.16.81.197:3306/gitauth?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: gitauth
    password: gitauth12#$

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql: trace